### ISSUE TITLE
auto-installation

### ISSUE THREAD

**Issue by stevengj** [crbinz/SGP4.jl#5]
You should probably be doing something like `pyimport_conda("sgp4", "sgp4")` in your `__init__` function to auto-install the SGP4 package via Conda if possible.  (Requires PyCall 1.5.)

Though it looks like sgp4 is only available in a custom Conda channel.   To make this possible, I'll add a third argument to `pyimport_conda` in PyCall 1.6 so that you can do `pyimport_conda("sgp4", "sgp4", "poliastro")` to use the poliastro channel.

**Comment by stevengj** [comment]
Okay, PyCall 1.6 should be tagged shortly, and then you can automate installation via `pyimport_conda("sgp4", "sgp4", "poliastro")`

**Comment by crbinz** [comment]
Finally got around to this -- that was easy! Thanks.

**Comment by stevengj** [comment]
I would recommend something like what the PyCall README says:

``` jl
const sgp4io = PyNULL()
const earth_gravity = PyNULL()
function __init__()
    copy!(sgp4io, pyimport_conda("sgp4.io", "sgp4", "poliastro"))
    copy!(earth_gravity, pyimport("sgp4.earth_gravity"))
end
```

and then you can do e.g. `twoline2rv(args...) = sgp4io["twoline2rv"](args...)` and `GravityModel(ref::AbstractString) = earth_gravity["ref"]`.

This is more type-stable and should also be faster because you don't need to have `pywrap` convert every single object defined in the module.

Note also that `pyimport_conda` already gives a [useful error message](https://github.com/JuliaPy/PyCall.jl/blob/b050d9416193e0c43d707fdf477ee059d087d77a/src/PyCall.jl#L490-L496), so you don't need your own.

**Comment by crbinz** [comment]
Awesome, thanks for the tips.
